### ISSUE TITLE
Sync Up Existing Test Suites with x-common

### ISSUE THREAD

**Issue by abo64** [exercism/scala#331]
There are continuous changes of existing tests in x-common.
Is there a good way to keep track and update the Scala tests?

Just to list some recent changes:
- [x] scrabble-score
- [x] nucleotide-count
- [x] phone-number
- [x] prime-factors
- [x] etl
- [x] secret-handshake

**Comment by ErikSchierboom** [comment]
Coincidentally, an issue for this topic has only recently been opened: https://github.com/exercism/x-common/issues/524 Perhaps you could chip in there?

**Comment by abo64** [comment]
What do you think about the idea to directly parse the `canonical-data.json` file as suggested in [this Haskell issue](https://github.com/exercism/xhaskell/pull/487)?

**Comment by ricemery** [comment]
I think we should generate the tests programmatically. Some of the test
suites are already built in this way.
Take a look in the testgen directory and
https://github.com/exercism/xscala/blob/master/README.md . The testgen code
I have written isn't all that clean, but it works.

**Comment by abo64** [comment]
@ricemery Yes, that looks like the right idea.

I wonder whether we should even bother to generate extra Scala source code from the `TestCase`s as it complicates matters quite a bit.
Maybe just use the `TestCase`s to run the tests immediately? (very similar to the Haskell PR).

(btw, you use `play.api.libs.json`. Why?)

**Comment by ricemery** [comment]
If I understand the Haskell PR correctly, they want their test code to read the JSON and build/execute test cases dynamically.
I'm not sure I like that idea. It add complexity for the end user trying to figure out how to code their solution to meet the test requirements. When I solve exercism problems, I always look at the test code to figure out how to proceed. I suppose this is TDD.
I think having the test cases obfuscated within the JSON makes doing TDD more difficult.

Though I do agree it would make maintaining the test suites easier.

I am using play json because I knew how to use the api. It is in no way a statement on play json being the best way to parse json.

**Comment by abo64** [comment]
True, this approach works only if a closer look at the test suite is not required (which is the case in the Haskell track). Some issues:
- Every exercise includes a stub with the signature for the solution;
or if we don't want this we need a unified format of the tests that makes it very clear how the solution signature must be: For example always having a (possibly overloaded) function named `callMUT` or so that then calls and reveals the required signature(s).
- The test failure messages must be self-explanatory including input, expected and actual output.
- There are no `pending` exercises (which I personally would welcome - one usually tries to go through the tests from top to bottom anyway to make them green).
- Maybe some additional general information about all this on how to run a test suite.

I agree that these are a quite disruptive changes, and that might be reason enough to not go this way.
On the other hand the extra step of creating a Scala source file adds quite some complexity and work for ourselves. Is it really worth the effort?

**Comment by ErikSchierboom** [comment]
Creating a Scala source is more work, but I really feel we should keep it that way. Every single exercise I try to solve, I start out with examining the tests. I really like having them be explicit and being able to run or debug them individually.

To solve the problem of automatically keeping up-to-date with the canonical data, I think a better approach would be to write a generator that takes the canonical data and automatically creates the test file.

**Comment by abo64** [comment]
All right, if that is the majority opinion I will of course follow.
I will look upon it as a challenge to simplify this translation process. :)

**Comment by ricemery** [comment]
I'm sure you can do a much better job of building a generator than I did! I
will admit that my generators are ugly.

**Comment by abo64** [comment]
No, that is fine.
I was thinking to extract some utility functions or so. Your generators are a good start!

**Comment by abo64** [comment]
Now the x-common JSON schema has become more standardized.

My suggestion is:
We track progress of [this issue](https://github.com/exercism/x-common/issues/625) and update the Scala test suites more or less in sync with it, ideally adding respective test generators.
Even better would be to make use of the schema versions somehow?

What do you think?

**Comment by ErikSchierboom** [comment]
So are you suggesting that we should make the basic test generator conform to the updated JSON schema?

**Comment by abo64** [comment]
@ErikSchierboom Not really, but when I think about it: This is actually a good idea, too! :)
We could do this first. Probably with a clone of `TestBuilder` (named `TestSuiteBuilder`, say) in order not to interfere with existing generators.

As this issue is about being in sync with changes in x-common: My initial thought was only to monitor the issue and update our generators and test suites more or less in sync with it.
Or if we somehow keep track of the json file versionIds (for example as a comment in the test suite?) we might even be able to automatically generate the list of outdated test suites?

**Comment by rbasso** [comment]
We are not supposed to change the test data in exercism/x-common#625, except for adding the `property` key and maybe make other minor changes to pass validation. I'm also taking the opportunity no reformat the files in separated commits.

If any PR there changes the test contents, *it is a bug*. 🐛 

Of course, all the current generators will almost certainly stop functioning.

**Comment by abo64** [comment]
@rbasso You are right. Maybe I should then say:
Let's use the changes of tests in exercism/x-common#625 to
- write/adapt Scala test generators for them.
- cover any changes of outdated Scala test suites on the fly.
- detect any future changes automatically if we can to keep the Scala test suites up to date.

**Comment by ErikSchierboom** [comment]
Sounds like a good plam!

**Comment by abo64** [comment]
[TestCaseGen](https://github.com/exercism/xscala/blob/master/testgen/src/main/scala/TestBuilder.scala#L4) should be modified to contain all possible json schema fields.
And the Json parser can be included in `TestSuiteBuilder` to always (?!) create the `Seq[TestCaseGen]`.

Then hopefully the default generator will just work for most test suites.

**Comment by rbasso** [comment]
> TestCaseGen should be modified to contain all possible json schema fields.
And the Json parser can be included in TestSuiteBuilder to always (?!) create the Seq[TestCaseGen].
>
>Then hopefully the default generator will just work for most test suites.

I just remembered one important thing...

One of the central features of the new schema is that test data is completely separated from test grouping, so it is possible to write generators that are not sensible to test grouping, and they would continue working if the tests are regrouped/"renested", which is not considered a MAJOR change. In fact, if the test ordering is not changed, regrouping is considered simply a PATCH by the [proposed semantic versioning](exercism/x-common#673).

**Comment by ricemery** [comment]
@abo64 , @ErikSchierboom ,

I was looking to update `perfect-numbers` to use the canonical-data.json. I notice that the last 2 test cases are testing error conditions. The existing test suite and solution do not test error conditions. I am trying to decide how to proceed.

I could have the code/tests handle optional or either. But.. We have this exercise set as a difficulty 2. I'm not sure we want to introduce optional or either in a difficulty 2 exercise. So, we would probably want to move the difficulty to 3.

Or, the code could throw an exception. Which doesn't feel right..

Or, the NumberType enumeration could have an additional value of `Error`. And, the error tests could check for the `Error` value.

Thoughts?

Thanks

**Comment by abo64** [comment]
IMO the the right way to represent this in Scala would be with `Either` as the test cases define precise error messages. If there is no error message as for [all-your-base](https://github.com/exercism/x-common/blob/master/exercises/all-your-base/canonical-data.json#L95) it would be translated to an `Option`.

And yes, then the difficulty should be increased to 3.

**Comment by ErikSchierboom** [comment]
I agree with @abo64!

**Comment by ricemery** [comment]
Thanks @abo64  and @ErikSchierboom !
