### ISSUE TITLE
Add Version Numbers to Test Suites

### ISSUE THREAD

**Issue by abo64** [exercism/scala#370]
Follow-up of #331: In order to keep in sync with `x-common` we need to add the version number of the respective `canonical-data.json` to all existing test suites (N.B. in addition we also need a script to detect out-of-sync test suites). For the exact format see [HelloWorldTest.scala](https://github.com/exercism/xscala/blob/master/exercises/hello-world/src/test/scala/HelloWorldTest.scala#L3).
Preferably this could be done by writing a test suite generator using [TestSuiteBuilder](https://github.com/exercism/xscala/blob/master/testgen/src/main/scala/testgen/TestSuiteBuilder.scala), but a simple manual (update of the test suite and) addition of the version number might do for now, too.

A few exercises already have a test suite generator using `TestSuiteBuilder` but don't contain the version number, so they are still unchecked.
- [x] accumulate
- [x] acronym
- [x] all-your-base
- [x] allergies
- [x] alphametics
- [x] anagram
- [x] atbash-cipher
- [x] bank-account
- [x] beer-song
- [x] binary-search-tree
- [x] binary-search
- [ ] binary
- [x] bob
- [x] bowling
- [x] bracket-push
- [x] change
- [x] clock
- [x] connect
- [x] crypto-square
- [x] custom-set
- [x] difference-of-squares
- [x] dominoes
- [x] etl
- [x] food-chain
- [x] forth
- [x] gigasecond
- [x] grade-school
- [x] grains
- [x] hamming
- [x] hello-world
- [ ] hexadecimal
- [x] house
- [x] isogram
- [x] kindergarten-garden
- [x] largest-series-product
- [x] leap
- [x] lens-person
- [x] linked-list
- [x] luhn
- [x] matrix
- [x] meetup
- [x] minesweeper
- [x] nth-prime
- [x] nucleotide-count
- [x] ocr-numbers
- [ ] octal
- [x] palindrome-products
- [x] pangram
- [x] parallel-letter-frequency
- [x] pascals-triangle
- [x] perfect-numbers
- [x] phone-number
- [x] pig-latin
- [x] prime-factors
- [x] protein-translation
- [x] pythagorean-triplet
- [x] queen-attack
- [x] rail-fence-cipher
- [x] raindrops
- [x] rna-transcription
- [x] robot-name
- [x] robot-simulator
- [x] roman-numerals
- [x] run-length-encoding
- [x] saddle-points
- [x] say
- [x] scrabble-score
- [x] secret-handshake
- [x] series
- [x] sgf-parsing
- [x] sieve
- [x] simple-cipher
- [x] simple-linked-list
- [x] space-age
- [x] strain
- [x] sublist
- [x] sum-of-multiples
- [x] triangle
- [ ] trinary
- [x] variable-length-quantity
- [x] word-count
- [x] wordy
- [x] zebra-puzzle
- [x] zipper

**Comment by ricemery** [comment]
@ErikSchierboom - what do you think we should do about the exercises that do not have canonical-data?
 Should we leave the version tag out? I don't think we should put in version 1.0.0. That would be wrong. 
I think it would be nice to be able to look at a test and know it did NOT come from canonical-data. No info in the test makes it confusing as to where the test came from. Maybe something like

`/** @version manual **/` 
`/** @version hand-generated **/`

Ideas?

**Comment by ErikSchierboom** [comment]
I agree with putting in something. As for the actual text, maybe: `/** @version created manually **/`?

**Comment by ricemery** [comment]
That will work. I will start adding -

/** @version created manually **/

Thanks

**Comment by ricemery** [comment]
Fixed - no need to change 

* binary
* hexadecimal
* octal
* trinary

These are all deprecated. And, not included in config.json.
