### ISSUE TITLE
Many exercises don't have main.scala files, only .keep files

### ISSUE THREAD

**Issue by dj168** [exercism/scala#484]
A few examples:

https://github.com/exercism/scala/tree/master/exercises/flatten-array/src/main/scala
https://github.com/exercism/scala/tree/master/exercises/robot-simulator/src/main/scala

**Comment by kytrinyx** [comment]
I don't know if this is intentional in the Scala track, but in many Exercism tracks, only the first few exercises have a stubbed solution file. After a while, we're assuming that people are able to follow the error messages to create their own solution from scratch.

**Comment by ricemery** [comment]
This is "by design". We only stubbed a handful of exercises. We intended
for the implementers to determine the expected function signatures from the
unit tests for the remaining exercises.
