### ISSUE TITLE
Some Exercises Doesn't have main Scala file present.

### ISSUE THREAD

**Issue by shankarshastri** [exercism/scala#587]
Do we want to implement the methods in the src/main folder? If yes, I can take a look at it.
Implement As Such I mean, for example:
AllYourBase.scala
```scala
object AllYourBase {
def rebase(s: Int, l: List[Int], k: Int) = ???
}
```

**Comment by ricemery** [comment]
Thank you for the offer, but we choose not to implement stubs for most of
the exercises. We leave this to each student.

**Comment by shankarshastri** [comment]
Valid Point. Closing this issue.
