### ISSUE TITLE
Static method in FoodChain tests

### ISSUE THREAD

**Issue by camilopayan** [exercism/scala#601]
The tests for the FoodChain exercise appear to rely on a static `recite` method but after some research, it seems like static methods are not part of the Scala language. This would be fixed by instantiating the FoodChain object under test, I think.

```
  test("fly") {
    FoodChain.recite(1, 1) should be ("""I know an old lady who swallowed a fly.
I don't know why she swallowed the fly. Perhaps she'll die.

""")
  }
```

**Comment by ricemery** [comment]
Have you tried defining your FoodChain solution using 'Object' and not 'Class'?

**Comment by camilopayan** [comment]
!!! closing.
