### ISSUE TITLE
Can't resovle sbt library for scalaz-core 7.2.6

### ISSUE THREAD

**Issue by counter2015** [exercism/scala#621]
In this problem, scala track, side exercise `Lens Person` :

`exercism download --exercise=lens-person --track=scala`

In `build.sbt`
```scala
scalaVersion := "2.12.8"
  
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.1" % "test"

val monocleVersion = "1.4.0-M2"

libraryDependencies ++= Seq(
  "com.github.julien-truffaut" %%  "monocle-core"  % monocleVersion,
  "com.github.julien-truffaut" %%  "monocle-macro" % monocleVersion)

libraryDependencies += "org.scalaz" %% "scalaz-core" % "7.2.5"

```

However, maven central repository can't find this vesion package.

https://repo1.maven.org/maven2/org/scalaz/scalaz-core_2.12/

How about change it to another version?

**Comment by ricemery** [comment]
@counter2015  - I have created a pull request to change the Monocle version to 2.0 and the ScalaZ version to 7.2.28.

I was able to test successfully using these versions and SBT. I was not able to run the tests using IntelliJ. I don't have spare cycles to localize the problem with IntelliJ at this point.

**Comment by counter2015** [comment]
@ricemery I have test it on my local IntelliJ environment, it seems to work successfully.

![](https://user-images.githubusercontent.com/13608862/65014050-edfdfc80-d94f-11e9-9a78-e5337e994942.png)

**Comment by ricemery** [comment]
Thanks @counter2015
