### ISSUE TITLE
Broken link in robot-name exercise

### ISSUE THREAD

**Issue by RodrigoCSoares** [exercism/scala#626]
The [robot-name exercise](https://github.com/exercism/scala/tree/master/exercises/robot-name) has a broken link to http://gschool.it under the "Source" section of the exercise.

**Comment by ErikSchierboom** [comment]
Thanks for catching this! Would you be willing to submit a PR to fix this? If so, the file you want to update is https://github.com/exercism/scala/blob/master/exercises/robot-name/README.md
