### ISSUE TITLE
Recruiting additional maintainers for Scala

### ISSUE THREAD

**Issue by kytrinyx** [exercism/scala#628]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by ErikSchierboom** [comment]
I'm an existing maintainer and I would love to help!

**Comment by ricemery** [comment]
I would love to. But.. All my exercism time is being spent on mentoring.
Most weeks I am mentoring between 90-100% of the Scala exercises that get
mentored. If we can accept a slow down on number of exercises mentored,
then I can switch gears into maintainer mode.

**Comment by ErikSchierboom** [comment]
> If we can accept a slow down on number of exercises mentored,
then I can switch gears into maintainer mode.

This would absolutely have our preference! Part of the goal of v3 is to make the mentoring pressure disappear for a large part, so we'd love it if you'd go into maintainer mode.
