### ISSUE TITLE
Exercism Scala projects don't work with brew installed Scala and SBT

### ISSUE THREAD

**Issue by m-c-g** [exercism/scala#634]
I initially had a problem with build.sbt having an older version of scala listed than that installed by brew. I fixed that and now there are problems with ScalaTest.  Matchers and FunSuite are not being found.

**Comment by LarsWestergren** [comment]
This can be closed I think, since main now uses sbt 1.7.1 and Scala 2.13.6. I asked a colleague who uses Mac to verify, and he had no problems.
