### ISSUE TITLE
Support of Scala 2.13 (or even better 3.0)

### ISSUE THREAD

**Issue by nartamonov** [exercism/scala#678]
Hi all! I'm joined the scala track and was sad to see that most of the exercises use rather old version of Scala: 2.12. Why is it? I expected 2.13. By the way, Scala 3.0 was released not long ago.

**Comment by LarsWestergren** [comment]
This was created before https://github.com/exercism/scala/issues/684 but since discussions are done there, suggest closing this one.

**Comment by ErikSchierboom** [comment]
Superseded by #684
